/* Anthony Capo - acapo */

/* Query A */
SELECT *
FROM CUSTOMER;

/* Query B */
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER;

/* Query C */
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER
WHERE FIRSTNAME = 'Nikki';

/* Query D */
SELECT LASTNAME, FIRSTNAME, PHONE, DATEIN, DATEOUT
FROM INVOICE
WHERE TOTALAMOUNT > 100;

/* Query E */
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER
WHERE FIRSTNAME LIKE 'B%';

/* Query F */
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER
WHERE LASTNAME LIKE '%cat%';

/* Query G */
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER
WHERE PHONE LIKE '?23*';

/* Query H */
SELECT MAX(TOTALAMOUNT) AS MaxTotalAmt,
			MIN(TOTALAMOUNT) AS MinTotalAmt
FROM INVOICE;

/* Query I */
SELECT AVG(TOTALAMOUNT) AS AvgTotalAmt
FROM [ORDER];

/* Query J */
SELECT Count(*) AS NumberOfCusts
FROM CUSTOMER;

/* Query K */
SELECT LASTNAME, FIRSTNAME
FROM CUSTOMER
GROUP BY LASTNAME, FIRSTNAME;

/* Query L */
SELECT LASTNAME, FIRSTNAME
		Count (*) AS LastAndFirst
FROM CUSTOMER
GROUP BY LASTNAME, FIRSTNAME;
