/* Anthony Capo - acapo */

/* Query M */
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER, INVOICE
WHERE TOTALAMOUNT IN 
					(SELECT TOTALAMOUNT
                    FROM INVOICE
                    WHERE TOTALAMOUNT > 100)
ORDER BY LASTNAME ASC, FIRSTNAME DESC;
                    
/* Query N */
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER, INVOICE
WHERE CUSTOMER.CustomerID=INVOICE.CustomerNumber
WHERE TOTALAMOUNT > 100
ORDER BY LASTNAME ASC, FIRSTNAME DESC;

/* Query O */ 
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER JOIN INVOICE 
ON CUSTOMER.CustomerID=INVOICE.CustomerNumber
WHERE TOTALAMOUNT > 100
ORDER BY LASTNAME ASC, FIRSTNAME DESC;

/* Query P */
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER
WHERE CUSTOMERID IN
			(SELECT CUSTOMERNUMBER
            FROM INVOICE
            WHERE INVOICENUMBER IN
								(SELECT INVOICENUMBER
                                FROM INVOICE_ITEM
                                WHERE ITEM = 'DRESS SHIRT'))
ORDER BY LASTNAME ASC, FIRSTNAME DESC;

/* Query Q */
SELECT LASTNAME, FIRSTNAME, PHONE
FROM CUSTOMER, INVOICE_ITEM
WHERE CUSTOMER.CustomerID=INVOICE_ITEM.CustomerNumber
WHERE INVOICE_ITEM='DRESS SHIRT'
ORDER BY LASTNAME ASC, FIRSTNAME DESC;

/* Query R */
SELECT LASTNAME, FIRSTNAME, TOTALAMOUNT
FROM CUSTOMER, INVOICE
WHERE CUSTOMER.Phone=INVOICE.Phone
AND INVOICE.Number IN
			(SELECT Number
            FROM INVOICE_ITEM
            WHERE Item='DRESS SHIRT')
ORDER BY LASTNAME ASC, FIRSTNAME DESC;

/* Query T */
SELECT LASTNAME, FIRSTNAME, PHONE, TOTALAMOUNT
FROM ((CUSTOMER
INNER JOIN INVOICE ON CUSTOMER.CustomerID = INVOICE.CustomerNumber)
LEFT JOIN INVOICE_ITEM ON INVOICE.InvoiceNumber = INVOICE_ITEM.InvoiceNumber 
                      AND INVOICE_ITEM.Item ='DRESS SHIRT')
ORDER BY LASTNAME ASC, FIRSTNAME DESC;

           